// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV44tjI2k34iVXf-uLKApNliTNQ0zamZM',
    appId: '1:780268668893:web:de8d2a750e6d7113e25834',
    messagingSenderId: '780268668893',
    projectId: 'quanlysinhvien-e9b2c',
    authDomain: 'quanlysinhvien-e9b2c.firebaseapp.com',
    storageBucket: 'quanlysinhvien-e9b2c.appspot.com',
    measurementId: 'G-SPHDL962TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIhwfemSGdpqs3I3bld1o709ZllUJWdFg',
    appId: '1:780268668893:android:742be59a5c3c845de25834',
    messagingSenderId: '780268668893',
    projectId: 'quanlysinhvien-e9b2c',
    storageBucket: 'quanlysinhvien-e9b2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqSC8RpZFsyDRzjshGX0PKUVyhgbrPI8o',
    appId: '1:780268668893:ios:e0bfb2e7e976f9aee25834',
    messagingSenderId: '780268668893',
    projectId: 'quanlysinhvien-e9b2c',
    storageBucket: 'quanlysinhvien-e9b2c.appspot.com',
    iosBundleId: 'com.example.quanlysinhvien',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqSC8RpZFsyDRzjshGX0PKUVyhgbrPI8o',
    appId: '1:780268668893:ios:e0bfb2e7e976f9aee25834',
    messagingSenderId: '780268668893',
    projectId: 'quanlysinhvien-e9b2c',
    storageBucket: 'quanlysinhvien-e9b2c.appspot.com',
    iosBundleId: 'com.example.quanlysinhvien',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV44tjI2k34iVXf-uLKApNliTNQ0zamZM',
    appId: '1:780268668893:web:5553f3f6b62bfb54e25834',
    messagingSenderId: '780268668893',
    projectId: 'quanlysinhvien-e9b2c',
    authDomain: 'quanlysinhvien-e9b2c.firebaseapp.com',
    storageBucket: 'quanlysinhvien-e9b2c.appspot.com',
    measurementId: 'G-TS2011EZ6L',
  );
}
